=== BeaFontan/Clase/0 - Primero/Lenguajes/0 - 2da Evaluación/3 - XML/XSD/Ejercicio 16 - familia/familias.xsd
<<<<<<< HEAD
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="familias">
 
        <xs:complexType>

            <xs:sequence>
                <xs:element name="familia" minOccurs="0" maxOccurs="unbounded">
                    <!-- Defino los elementos de familia -->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="padres">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="padre" minOccurs="0" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                                                    <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="2"></xs:element>
                                                    <xs:element name="dni" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d{2}\.\d{3}\.\d{3}\-[A-Za-z]"></xs:pattern>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="edad" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                            

                                        <xs:element name="madre" type="xs:string" minOccurs="0" maxOccurs="2"></xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="hijos" type="datos_hijos"></xs:element>

                            
                        </xs:sequence>



                        <!-- Defino el atributo de familia -->
                        <xs:attribute name="codigo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                <xs:pattern value="[A-Z]\d{2}\-\d{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType> 
                    
                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>



    
=======
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="orderperson" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="address" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
<xs:element name="country" type="xs:string"/>
<xs:element name="title" type="xs:string"/>
<xs:element name="note" type="xs:string"/>
<xs:element name="quantity" type="xs:positiveInteger"/>
<xs:element name="price" type="xs:decimal"/>


<!-- definition of attributes -->
<xs:attribute name="orderid" type="xs:string"/>

<!-- definition of complex elements -->
<xs:element name="shipto">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="address"/>
      <xs:element ref="city"/>
      <xs:element ref="country"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="item">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="title"/>
      <xs:element ref="note" minOccurs="0"/>
      <xs:element ref="quantity"/>
      <xs:element ref="price"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="shiporder">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="orderperson"/>
      <xs:element ref="shipto"/>
      <xs:element ref="item" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute ref="orderid" use="required"/>
  </xs:complexType>
</xs:element>

>>>>>>> refs/remotes/origin/main
</xs:schema>

=== BeaFontan/Clase/Lenguajes de marcas/0 - 2da Evaluación/3 - XML/XSD/Ejercicio 16 - familia/index.xml
<?xml version="1.0" encoding="UTF-8" ?>
<shiporder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="familias.xsd"
           orderid="123">
    <orderperson>John Doe</orderperson>
    <shipto>
        <name>Receiver Name</name>
        <address>123 Street Name</address>
        <city>City</city>
        <country>Country</country>
    </shipto>
    <item>
        <title>Some Product</title>
        <note>Optional note</note>
        <quantity>2</quantity>
        <price>10.99</price>
    </item>
    <!-- You can have multiple <item> elements -->
    <item>
        <title>Another Product</title>
        <quantity>1</quantity>
        <price>20.50</price>
    </item>
</shiporder>

=== BeaFontan/Clase/0 - Primero/Lenguajes/0 - 2da Evaluación/3 - XML/XSD/Ejercicio 16 - familia/index.xml
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<familias xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="familias.xsd">
    <familia codigo="P01-07">
        <padres>
            <padre>
                <nombre>Antonio</nombre>
                <apellido>Pérez</apellido>
                <apellido>Castro</apellido>
                <dni>32.234.345-D</dni>
                <edad>35</edad>
            </padre>
            <padre>
                <nombre>Luis</nombre>
                <apellido>Ramos</apellido>
                <apellido>López</apellido>
                <dni>32.556.767-B</dni>
                <edad>38</edad>
            </padre>
        </padres>
        <hijos>

            <hijo pos="2">
                <nombre>Clara</nombre>
                <dni>44.556.767-B</dni>
                <edad>5</edad>
            </hijo>

            <hija pos="1">
                <nombre>Jorge</nombre>
                <dni>44.556.768-B</dni>
                <edad>8</edad>
            </hija>
        </hijos>
    </familia>

    <familia codigo="P01-02">
        <padres>
            <madre>
                <nombre>Laura</nombre>
                <apellido>Porto</apellido>
                <apellido>Abelleira</apellido>
                <dni>32.222.333-L</dni>
            </madre>
        </padres>

        <hijos>
            <hija pos="1">
            <nombre>Carmen</nombre>
            <edad>2</edad>
            </hija>
        </hijos>
    </familia>

    <familia codigo="P01-04">
        <padres>
            <madre>
                <nombre>Rosa</nombre>
                <apellido>González</apellido>
                <apellido>Pombo</apellido>
                <dni>33.456.765-D</dni>
                <edad>27</edad>
            </madre>
            <padre>
                <nombre>Manuel</nombre>
                <apellido>Solmo</apellido>
                <apellido>Hermida</apellido>
                <dni>34.846.112-L</dni>
            </padre>
        </padres>
        <hijos>
            <hija pos="1">
            <nombre>Julieta</nombre>
            <edad>2</edad>
            </hija>
        </hijos>
    </familia>

</familias>
=======
<?xml version="1.0" encoding="UTF-8" ?>
<shiporder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="familias.xsd"
           orderid="123">
    <orderperson>John Doe</orderperson>
    <shipto>
        <name>Receiver Name</name>
        <address>123 Street Name</address>
        <city>City</city>
        <country>Country</country>
    </shipto>
    <item>
        <title>Some Product</title>
        <note>Optional note</note>
        <quantity>2</quantity>
        <price>10.99</price>
    </item>
    <!-- You can have multiple <item> elements -->
    <item>
        <title>Another Product</title>
        <quantity>1</quantity>
        <price>20.50</price>
    </item>
</shiporder>
>>>>>>> refs/remotes/origin/main
